site_name: VenafiPS
theme:
  name: material
  logo: images/v.svg
  features:
    - navigation.expand
  palette:
    primary: indigo
repo_url: https://github.com/Venafi/VenafiPS
repo_name: VenafiPS
edit_uri: ""
docs_dir: docs
markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
nav:
  - Home: index.md
  - Changelog: changelog.md
  - Functions:
    - Add-TppCertificateAssociation: functions/Add-TppCertificateAssociation.md
    - Add-VenafiTeamMember: functions/Add-VenafiTeamMember.md
    - Add-VenafiTeamOwner: functions/Add-VenafiTeamOwner.md
    - Convert-TppObject: functions/Convert-TppObject.md
    - ConvertTo-TppGuid: functions/ConvertTo-TppGuid.md
    - ConvertTo-TppPath: functions/ConvertTo-TppPath.md
    - Export-VenafiCertificate: functions/Export-VenafiCertificate.md
    - Find-TppClient: functions/Find-TppClient.md
    - Find-TppCodeSignEnvironment: functions/Find-TppCodeSignEnvironment.md
    - Find-TppCodeSignProject: functions/Find-TppCodeSignProject.md
    - Find-TppCodeSignTemplate: functions/Find-TppCodeSignTemplate.md
    - Find-TppIdentity: functions/Find-TppIdentity.md
    - Find-TppObject: functions/Find-TppObject.md
    - Find-TppVaultId: functions/Find-TppVaultId.md
    - Find-VenafiCertificate: functions/Find-VenafiCertificate.md
    - Get-TppAttribute: functions/Get-TppAttribute.md
    - Get-TppClassAttribute: functions/Get-TppClassAttribute.md
    - Get-TppCodeSignConfig: functions/Get-TppCodeSignConfig.md
    - Get-TppCodeSignEnvironment: functions/Get-TppCodeSignEnvironment.md
    - Get-TppCodeSignProject: functions/Get-TppCodeSignProject.md
    - Get-TppCredential: functions/Get-TppCredential.md
    - Get-TppCustomField: functions/Get-TppCustomField.md
    - Get-TppIdentityAttribute: functions/Get-TppIdentityAttribute.md
    - Get-TppObject: functions/Get-TppObject.md
    - Get-TppPermission: functions/Get-TppPermission.md
    - Get-TppSystemStatus: functions/Get-TppSystemStatus.md
    - Get-TppVersion: functions/Get-TppVersion.md
    - Get-TppWorkflowTicket: functions/Get-TppWorkflowTicket.md
    - Get-VaasApplication: functions/Get-VaasApplication.md
    - Get-VaasIssuingTemplate: functions/Get-VaasIssuingTemplate.md
    - Get-VenafiCertificate: functions/Get-VenafiCertificate.md
    - Get-VenafiIdentity: functions/Get-VenafiIdentity.md
    - Get-VenafiTeam: functions/Get-VenafiTeam.md
    - Import-TppCertificate: functions/Import-TppCertificate.md
    - Import-VaasCertificate: functions/Import-VaasCertificate.md
    - Invoke-TppCertificatePush: functions/Invoke-TppCertificatePush.md
    - Invoke-TppCertificateRenewal: functions/Invoke-TppCertificateRenewal.md
    - Invoke-VenafiCertificateAction: functions/Invoke-VenafiCertificateAction.md
    - Invoke-VenafiRestMethod: functions/Invoke-VenafiRestMethod.md
    - Move-TppObject: functions/Move-TppObject.md
    - New-TppCapiApplication: functions/New-TppCapiApplication.md
    - New-TppCertificate: functions/New-TppCertificate.md
    - New-TppCodeSignProject: functions/New-TppCodeSignProject.md
    - New-TppCustomField: functions/New-TppCustomField.md
    - New-TppDevice: functions/New-TppDevice.md
    - New-TppObject: functions/New-TppObject.md
    - New-TppPolicy: functions/New-TppPolicy.md
    - New-TppToken: functions/New-TppToken.md
    - New-VaasApplication: functions/New-VaasApplication.md
    - New-VenafiSession: functions/New-VenafiSession.md
    - New-VenafiTeam: functions/New-VenafiTeam.md
    - Read-VenafiLog: functions/Read-VenafiLog.md
    - Remove-TppCertificate: functions/Remove-TppCertificate.md
    - Remove-TppCertificateAssociation: functions/Remove-TppCertificateAssociation.md
    - Remove-TppClient: functions/Remove-TppClient.md
    - Remove-TppCodeSignEnvironment: functions/Remove-TppCodeSignEnvironment.md
    - Remove-TppCodeSignProject: functions/Remove-TppCodeSignProject.md
    - Remove-TppPermission: functions/Remove-TppPermission.md
    - Remove-VenafiTeam: functions/Remove-VenafiTeam.md
    - Remove-VenafiTeamMember: functions/Remove-VenafiTeamMember.md
    - Remove-VenafiTeamOwner: functions/Remove-VenafiTeamOwner.md
    - Rename-TppObject: functions/Rename-TppObject.md
    - Revoke-TppCertificate: functions/Revoke-TppCertificate.md
    - Revoke-TppToken: functions/Revoke-TppToken.md
    - Search-TppHistory: functions/Search-TppHistory.md
    - Set-TppAttribute: functions/Set-TppAttribute.md
    - Set-TppCodeSignProjectStatus: functions/Set-TppCodeSignProjectStatus.md
    - Set-TppCredential: functions/Set-TppCredential.md
    - Set-TppPermission: functions/Set-TppPermission.md
    - Set-TppWorkflowTicketStatus: functions/Set-TppWorkflowTicketStatus.md
    - Test-ModuleHash: functions/Test-ModuleHash.md
    - Test-TppIdentity: functions/Test-TppIdentity.md
    - Test-TppObject: functions/Test-TppObject.md
    - Test-TppToken: functions/Test-TppToken.md
    - Write-TppLog: functions/Write-TppLog.md

