site_name: VenafiPS
site_url: https://venafi.github.io/venafips/
theme:
  name: material
  logo: images/v.svg
  features:
    - navigation.expand
  palette:
    primary: indigo
edit_uri: ""
nav:
  - Home: index.md
  - Changelog: changelog.md
  - Functions:
    - Add-VcTeamMember: functions/Add-VcTeamMember.md
    - Add-VcTeamOwner: functions/Add-VcTeamOwner.md
    - Add-VdcAdaptableHash: functions/Add-VdcAdaptableHash.md
    - Add-VdcCertificateAssociation: functions/Add-VdcCertificateAssociation.md
    - Add-VdcEngineFolder: functions/Add-VdcEngineFolder.md
    - Add-VdcTeamMember: functions/Add-VdcTeamMember.md
    - Add-VdcTeamOwner: functions/Add-VdcTeamOwner.md
    - Convert-VdcObject: functions/Convert-VdcObject.md
    - ConvertTo-VdcGuid: functions/ConvertTo-VdcGuid.md
    - ConvertTo-VdcPath: functions/ConvertTo-VdcPath.md
    - Export-VcCertificate: functions/Export-VcCertificate.md
    - Export-VdcCertificate: functions/Export-VdcCertificate.md
    - Export-VdcVaultObject: functions/Export-VdcVaultObject.md
    - Find-VcCertificate: functions/Find-VcCertificate.md
    - Find-VcCertificateInstance: functions/Find-VcCertificateInstance.md
    - Find-VcCertificateRequest: functions/Find-VcCertificateRequest.md
    - Find-VcLog: functions/Find-VcLog.md
    - Find-VcMachine: functions/Find-VcMachine.md
    - Find-VcMachineIdentity: functions/Find-VcMachineIdentity.md
    - Find-VdcCertificate: functions/Find-VdcCertificate.md
    - Find-VdcClient: functions/Find-VdcClient.md
    - Find-VdcEngine: functions/Find-VdcEngine.md
    - Find-VdcIdentity: functions/Find-VdcIdentity.md
    - Find-VdcObject: functions/Find-VdcObject.md
    - Find-VdcVaultId: functions/Find-VdcVaultId.md
    - Get-VcApplication: functions/Get-VcApplication.md
    - Get-VcCertificate: functions/Get-VcCertificate.md
    - Get-VcCertificateRequest: functions/Get-VcCertificateRequest.md
    - Get-VcConnector: functions/Get-VcConnector.md
    - Get-VcIssuingTemplate: functions/Get-VcIssuingTemplate.md
    - Get-VcMachine: functions/Get-VcMachine.md
    - Get-VcMachineIdentity: functions/Get-VcMachineIdentity.md
    - Get-VcSatellite: functions/Get-VcSatellite.md
    - Get-VcSatelliteWorker: functions/Get-VcSatelliteWorker.md
    - Get-VcTag: functions/Get-VcTag.md
    - Get-VcTeam: functions/Get-VcTeam.md
    - Get-VcUser: functions/Get-VcUser.md
    - Get-VcWebhook: functions/Get-VcWebhook.md
    - Get-VdcAttribute: functions/Get-VdcAttribute.md
    - Get-VdcCertificate: functions/Get-VdcCertificate.md
    - Get-VdcClassAttribute: functions/Get-VdcClassAttribute.md
    - Get-VdcCredential: functions/Get-VdcCredential.md
    - Get-VdcCustomField: functions/Get-VdcCustomField.md
    - Get-VdcEngineFolder: functions/Get-VdcEngineFolder.md
    - Get-VdcIdentity: functions/Get-VdcIdentity.md
    - Get-VdcIdentityAttribute: functions/Get-VdcIdentityAttribute.md
    - Get-VdcObject: functions/Get-VdcObject.md
    - Get-VdcPermission: functions/Get-VdcPermission.md
    - Get-VdcSystemStatus: functions/Get-VdcSystemStatus.md
    - Get-VdcTeam: functions/Get-VdcTeam.md
    - Get-VdcVersion: functions/Get-VdcVersion.md
    - Get-VdcWorkflowTicket: functions/Get-VdcWorkflowTicket.md
    - Import-VcCertificate: functions/Import-VcCertificate.md
    - Import-VdcCertificate: functions/Import-VdcCertificate.md
    - Invoke-VcCertificateAction: functions/Invoke-VcCertificateAction.md
    - Invoke-VcWorkflow: functions/Invoke-VcWorkflow.md
    - Invoke-VdcCertificateAction: functions/Invoke-VdcCertificateAction.md
    - Invoke-VenafiRestMethod: functions/Invoke-VenafiRestMethod.md
    - Move-VdcObject: functions/Move-VdcObject.md
    - New-VcApplication: functions/New-VcApplication.md
    - New-VcCertificate: functions/New-VcCertificate.md
    - New-VcConnector: functions/New-VcConnector.md
    - New-VcMachine: functions/New-VcMachine.md
    - New-VcMachineCommonKeystore: functions/New-VcMachineCommonKeystore.md
    - New-VcMachineIis: functions/New-VcMachineIis.md
    - New-VcTeam: functions/New-VcTeam.md
    - New-VcToken: functions/New-VcToken.md
    - New-VcWebhook: functions/New-VcWebhook.md
    - New-VdcCapiApplication: functions/New-VdcCapiApplication.md
    - New-VdcCertificate: functions/New-VdcCertificate.md
    - New-VdcCustomField: functions/New-VdcCustomField.md
    - New-VdcDevice: functions/New-VdcDevice.md
    - New-VdcObject: functions/New-VdcObject.md
    - New-VdcPolicy: functions/New-VdcPolicy.md
    - New-VdcTeam: functions/New-VdcTeam.md
    - New-VdcToken: functions/New-VdcToken.md
    - New-VenafiSession: functions/New-VenafiSession.md
    - Read-VdcLog: functions/Read-VdcLog.md
    - Remove-VcApplication: functions/Remove-VcApplication.md
    - Remove-VcCertificate: functions/Remove-VcCertificate.md
    - Remove-VcConnector: functions/Remove-VcConnector.md
    - Remove-VcIssuingTemplate: functions/Remove-VcIssuingTemplate.md
    - Remove-VcMachine: functions/Remove-VcMachine.md
    - Remove-VcMachineIdentity: functions/Remove-VcMachineIdentity.md
    - Remove-VcSatelliteWorker: functions/Remove-VcSatelliteWorker.md
    - Remove-VcTag: functions/Remove-VcTag.md
    - Remove-VcTeam: functions/Remove-VcTeam.md
    - Remove-VcTeamMember: functions/Remove-VcTeamMember.md
    - Remove-VcTeamOwner: functions/Remove-VcTeamOwner.md
    - Remove-VcWebhook: functions/Remove-VcWebhook.md
    - Remove-VdcCertificate: functions/Remove-VdcCertificate.md
    - Remove-VdcCertificateAssociation: functions/Remove-VdcCertificateAssociation.md
    - Remove-VdcClient: functions/Remove-VdcClient.md
    - Remove-VdcEngineFolder: functions/Remove-VdcEngineFolder.md
    - Remove-VdcObject: functions/Remove-VdcObject.md
    - Remove-VdcPermission: functions/Remove-VdcPermission.md
    - Remove-VdcTeam: functions/Remove-VdcTeam.md
    - Remove-VdcTeamMember: functions/Remove-VdcTeamMember.md
    - Remove-VdcTeamOwner: functions/Remove-VdcTeamOwner.md
    - Rename-VdcObject: functions/Rename-VdcObject.md
    - Revoke-VdcGrant: functions/Revoke-VdcGrant.md
    - Revoke-VdcToken: functions/Revoke-VdcToken.md
    - Search-VdcHistory: functions/Search-VdcHistory.md
    - Set-VcApplication: functions/Set-VcApplication.md
    - Set-VcCertificate: functions/Set-VcCertificate.md
    - Set-VcCertificateRequest: functions/Set-VcCertificateRequest.md
    - Set-VcConnector: functions/Set-VcConnector.md
    - Set-VcTeam: functions/Set-VcTeam.md
    - Set-VdcAttribute: functions/Set-VdcAttribute.md
    - Set-VdcCredential: functions/Set-VdcCredential.md
    - Set-VdcPermission: functions/Set-VdcPermission.md
    - Set-VdcWorkflowTicketStatus: functions/Set-VdcWorkflowTicketStatus.md
    - Test-VdcIdentity: functions/Test-VdcIdentity.md
    - Test-VdcObject: functions/Test-VdcObject.md
    - Test-VdcToken: functions/Test-VdcToken.md
    - Write-VdcLog: functions/Write-VdcLog.md

